all:
  hosts:
    node1:
      ansible_host: 192.168.99.10
    node2:
      ansible_host: 192.168.99.11
    node3:
      ansible_host: 192.168.99.12
  children:
    server:
      hosts:
        node1:
    dev:
      hosts:
        node2:
    prod:
      hosts:
        node3:
    client:
      children:
        dev:
        prod: