apiVersion: v1
kind: Service
metadata:
  name: nodejs_app-svc
  namespace: dev
spec:
  type: NodePort
  ports:
   - protocol: TCP
     targetPort: 80
     port: 80
     nodePort: 30009
  selector:
    app: nodejs_app