apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-svc
  namespace: {{ namespace_default }}
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: {{ container_Port }}
     nodePort: {{ nodeport_default }}
  selector:
    app: nodejs-app