apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-svc
  namespace: dev
spec:
  type: NodePort
  ports:
   - protocol: TCP
     targetPort: 8000
     port: 8000
     nodePort: 30009
  selector:
    app: nodejs_app