apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: {{ namespace_default }}
  labels:
    app: nodejs-app
    env: {{ namespace_default }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      name: pod-nodejs-app
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: matao39/node_app_devops:latest
          ports:    
            - containerPort: 8000
      nodeName: {{ node_Name }}
